### ISSUE TITLE
CustomSymbol::to_string shadows Display implementation

### ISSUE THREAD

**Issue by Caellian** [sam0x17/compile-symbol#3]
Standard `ToString` trait is implemented via:
`impl<T: fmt::Display + ?Sized> ToString for T {}`

Given that `Symbol: fmt::Display`, the `to_string` method is already implemented through `fmt::Display` and `CustomSymbol::to_string` is a duplicate definition.

**Comment by sam0x17** [comment]
IIRC I did this to avoid an extra allocation in one of those cases, but happy to accept a PR switching this around if there is a better way
